# GPYA iOS Podfile
platform :ios, '13.0'

# Cargamos los helpers de Flutter (Estándar obligatorio)
load File.expand_path(File.join('Flutter', 'generated_pod_helpers.rb'), __dir__)

install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Forzamos iOS 13.0 en todos los niveles para evitar errores de arquitectura
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
