platform :ios, '13.0'

# Cargamos los helpers de Flutter usando una ruta segura
podfile_dir = File.dirname(File.realpath(__FILE__))
load File.join(podfile_dir, 'Flutter', 'generated_pod_helpers.rb')

install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods podfile_dir
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
    end
  end
end
